---
name: run-goreleaser
description: Common tasks for running go-releaser

inputs:
  args:
    description: 'The go releaser command'
    required: true

runs:
  using: "composite"
  steps:
    # See https://goreleaser.com/blog/supply-chain-security/
    - uses: anchore/sbom-action/download-syft@da167eac915b4e86f08b264dbdbc867b61be6f0c #v0.20.5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"

    - uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a #v6.4.0
      with:
        distribution: goreleaser
        version: "v2.8.0"
        args: ${{ inputs.args }}
